import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{Menu,X,Heart,MapPin,Phone,Mail,ArrowRight,Landmark,CalendarDays,Users,Image as ImageIcon,Quote,Copy}from'lucide-react';import{content as c}from'./data/content';import'./styles.css';
const heroVideo='/assets/laxmi-meditation.mp4';
const img='https://images.unsplash.com/photo-1604608672516-f1b9c9a4f3a2?auto=format&fit=crop&w=1000&q=80';
function Navbar(){const[open,setOpen]=useState(false);let links=[['Home','home'],['About','about'],['Committee','committee'],['Donor','donor'],['Program','program'],['Donation','donation'],['Memories','memories'],['Founder','founder'],['Contact','contact']];return <nav><a className="brand" href="#home">ॐ <span>लक्ष्मी पूजा</span></a><button className="hamb" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div className={'navlinks '+(open?'show':'')}>{links.map(([n,id])=><a key={id} href={'#'+id} onClick={()=>setOpen(false)}>{n}</a>)}<a className="navdonate" href="#donation">सहयोग गर्नुहोस्</a></div></nav>}
function Section({id,eyebrow,title,children,light=false}){return <section id={id} className={light?'light':''}><div className="container"><div className="sectionhead"><span>{eyebrow}</span><h2>{title}</h2></div>{children}</div></section>}
function App(){return <><Navbar/><main>
<section id="home" className="hero"><video className="heroVideo" autoPlay muted loop playsInline preload="metadata" aria-hidden="true"><source src={heroVideo} type="video/mp4"/></video><div className="container heroGrid"><div className="heroCopy"><div className="eyebrow">शुभ दीपावली • शुभ लक्ष्मी पूजा</div><h1>{c.hero.title}</h1><p className="tagline">{c.hero.tagline}</p><div className="meta"><span><CalendarDays/> {c.hero.date}</span><span><MapPin/> {c.hero.location}</span></div><div className="actions"><a className="btn gold" href="#program">कार्यक्रम हेर्नुहोस् <ArrowRight/></a><a className="btn outline" href="#donation">पूजामा सहयोग गर्नुहोस्</a></div></div></div></section>
<Section id="about" eyebrow="परम्परा • श्रद्धा • सेवा" title={c.about.title} light><div className="twoCol"><div className="imageCard"><img src={img} alt="पूजा तथा सांस्कृतिक दृश्य"/></div><div className="aboutText"><p>{c.about.text}</p><div className="highlights"><div><Heart/>सामूहिक पूजा</div><div><Landmark/>धार्मिक परम्परा</div><div><Users/>समुदायको सहभागिता</div><div><Heart/>प्रसाद वितरण</div></div></div></div></Section>
<Section id="committee" eyebrow="हाम्रो टोली" title="पूजा व्यवस्थापन समिति"><div className="cards">{c.committee.map(([role,name],i)=><div className="person" key={i}><div className="avatar">ॐ</div><h3>{name}</h3><p>{role}</p><small>समिति सदस्य</small></div>)}</div></Section>
<Section id="donor" eyebrow="आभार • सम्मान • कृतज्ञता" title="श्री लक्ष्मी मूर्ति दाता" light><div className="donor"><div className="donorImage"><img src={img} alt="लक्ष्मी पूजा सांकेतिक चित्र"/></div><div><span className="goldLabel">{c.donor.title}</span><h2>{c.donor.name}</h2><p>{c.donor.text}</p><div className="ornament">✦ ✦ ✦</div></div></div></Section>
<Section id="program" eyebrow="समय • विधि • उत्सव" title="पूजा कार्यक्रम"><div className="timeline">{c.program.map(([time,title,desc],i)=><div className="event" key={i}><div className="dot">{String(i+1).padStart(2,'0')}</div><div className="eventBody"><time>{time}</time><h3>{title}</h3><p>{desc}</p><small>स्थान: [यहाँ स्थान राख्नुहोस्]</small></div></div>)}</div></Section>
<Section id="donation" eyebrow="सेवा • सहयोग • पारदर्शिता" title="पूजा सहयोग गर्नुहोस्"><div className="donateGrid"><div className="donateInfo"><h3>पूजा सहयोगका लागि विवरण</h3>{[['खाता धारक',c.donation.account],['बैंक',c.donation.bank],['खाता नम्बर',c.donation.number],['Digital Wallet',c.donation.wallet],['फोन नम्बर',c.donation.phone]].map(([k,v])=><div className="detail" key={k}><span>{k}</span><strong>{v}</strong><Copy size={15}/></div>)}</div><div className="qr"><div className="qrbox">QR</div><h3>Scan & Support</h3><p>QR Scan गरी पूजा आयोजनामा आफ्नो योगदान गर्नुहोस्।</p><button className="btn gold">सहयोग गर्नुहोस्</button></div></div></Section>
<Section id="memories" eyebrow="सम्झना • क्षण • इतिहास" title="विगतका पूजा सम्झनाहरू" light><div className="gallery">{c.memories.map((year,i)=><div className="galleryItem" key={year}><img src={img} alt={`विगतको पूजा ${year}`}/><div><span>पूजा वर्ष</span><strong>{year}</strong></div></div>)}</div></Section>
<Section id="founder" eyebrow="दृष्टि • योगदान • नेतृत्व" title="समिति संस्थापक"><div className="founder"><div className="founderPhoto"><img src={img} alt="संस्थापकको portrait placeholder"/></div><div><span className="goldLabel">{c.founder.title}</span><h2>{c.founder.name}</h2><p>{c.founder.bio}</p><blockquote><Quote/>{c.founder.quote}</blockquote></div></div></Section>
<Section id="contact" eyebrow="सम्पर्क • स्थान • सहभागिता" title="सम्पर्क तथा स्थान"><div className="contactGrid"><div className="map"><MapPin/><span>{c.contact.map}</span></div><div className="contactInfo"><div><MapPin/><p><b>ठेगाना</b>{c.contact.address}</p></div><div><Phone/><p><b>फोन</b>{c.contact.phone}</p></div><div><Mail/><p><b>इमेल</b>{c.contact.email}</p></div><div className="social"><span className="facebookMark" aria-label="Facebook">f</span><svg className="instagramIcon" aria-label="Instagram" viewBox="0 0 24 24" role="img" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg></div><form><input placeholder="नाम"/><input placeholder="फोन / इमेल"/><textarea placeholder="सन्देश"/><button className="btn gold" type="button">सन्देश पठाउनुहोस्</button></form></div></div></Section>
</main><footer><div className="container footerGrid"><div><div className="brand">ॐ <span>लक्ष्मी पूजा</span></div><p>श्रद्धा, समृद्धि र एकताको पवित्र उत्सव।</p></div><div><h4>Quick Navigation</h4><a href="#about">About</a><a href="#program">Program</a><a href="#donation">Donation</a><a href="#contact">Contact</a></div><div><h4>सम्पर्क</h4><p>{c.contact.phone}</p><p>{c.contact.email}</p></div></div><div className="copyright">© 2026 Laxmi Puja Committee • Designed & Developed by [नाम]</div></footer></>};createRoot(document.getElementById('root')).render(<App/>);
